apiVersion: v2
name: daskhub
icon: https://avatars3.githubusercontent.com/u/17131925?v=3&s=200
version: 0.0.1-set.by.chartpress
# appVersion is set to be a combination of the dependencies
appVersion: "jh3.1.0-dg2023.9.0"
description: Multi-user JupyterHub and Dask deployment.
dependencies:
  - name: jupyterhub
    version: "3.1.0"
    repository: https://jupyterhub.github.io/helm-chart/
    import-values:
      - child: rbac
        parent: rbac
  - name: dask-gateway
    version: "2023.9.0"
    repository: https://helm.dask.org/
maintainers:
  - name: Jacob Tomlinson (Nvidia)
    email: jtomlinson@nvidia.com
  - name: Joe Hamman (NCAR)
    email: jhamman@ucar.edu
  - name: Erik Sundell
    email: erik@sundellopensource.se
  - name: Tom Augspurger
    email: tom.w.augspurger@gmail.com
