{{- range $.Values.additional_worker_groups }}
{{- $worker := merge . $.Values.worker }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dask.fullname" $ }}-worker-{{ $worker.name }}
  labels:
    app: {{ template "dask.name" $ }}
    heritage: {{ $.Release.Service | quote }}
    release: {{ $.Release.Name | quote }}
    chart: {{ template "dask.chart" $ }}
    component: worker
spec:
  replicas: {{ $worker.replicas }}
  selector:
    matchLabels:
      app: {{ template "dask.name" $ }}
      release: {{ $.Release.Name | quote }}
      component: worker
  strategy:
    type: {{ $worker.strategy.type }}
  template:
    metadata:
      labels:
        app: {{ template "dask.name" $ }}
        release: {{ $.Release.Name | quote }}
        component: worker
      {{- with $worker.annotations }}
      annotations:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
    spec:
      {{- with $worker.image.pullSecrets }}
      imagePullSecrets:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with $worker.mounts.volumes }}
      volumes:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ template "dask.fullname" $ }}-worker
          image: "{{ $worker.image.repository }}:{{ $worker.image.tag }}"
          {{- with $worker.image.pullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          args:
            - {{ $worker.image.dask_worker }}
            {{- if $worker.custom_scheduler_url }}
            - {{ $worker.custom_scheduler_url }}
            {{- else }}
            - {{ template "dask.fullname" $ }}-scheduler:{{ $.Values.scheduler.servicePort }}
            {{- end }}
            {{- if $worker.resources.limits }}
            - --nthreads
            - {{ $worker.threads_per_worker | default $worker.resources.limits.cpu | default $worker.default_resources.cpu | quote }}
            - --memory-limit
            - {{ $worker.resources.limits.memory | default $worker.default_resources.memory | quote }}
            {{- end }}
            - --no-dashboard
            - --dashboard-address
            - {{ $worker.portDashboard | quote }}
            {{- with $worker.port }}
            - --worker-port
            - {{ . | quote }}
            {{- end }}
            {{- with $worker.extraArgs }}
            {{- . | toYaml | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: {{ $worker.portDashboard }}
              name: dashboard
          {{- with $worker.resources }}
          resources:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with $worker.env }}
          env:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with $worker.mounts.volumeMounts }}
          volumeMounts:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
      {{- with $worker.nodeSelector }}
      nodeSelector:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with $worker.securityContext }}
      securityContext:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with $worker.affinity }}
      affinity:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with $worker.tolerations }}
      tolerations:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with $worker.serviceAccountName }}
      serviceAccountName: {{ . | quote }}
      {{- end }}
---
{{- end }}
