{{- range $.Values.additional_worker_groups }}
{{- $worker := merge . $.Values.worker }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dask.fullname" $ }}-worker-{{ $worker.name }}
  labels:
    app: {{ template "dask.name" $ }}
    heritage: {{ $.Release.Service | quote }}
    release: {{ $.Release.Name | quote }}
    chart: {{ template "dask.chart" $ }}
    component: worker
spec:
  replicas: {{ $worker.replicas }}
  selector:
    matchLabels:
      app: {{ template "dask.name" $ }}
      release: {{ $.Release.Name | quote }}
      component: worker
  strategy:
    type: {{ $worker.strategy.type }}
  template:
    metadata:
      labels:
        app: {{ template "dask.name" $ }}
        release: {{ $.Release.Name | quote }}
        component: worker
      {{- if $worker.annotations }}
      annotations:
        {{- toYaml $worker.annotations | nindent 8 }}
      {{- end }}
    spec:
      imagePullSecrets:
        {{- toYaml $worker.image.pullSecrets | nindent 8 }}
      {{- if $worker.mounts.volumes }}
      volumes:
        {{- toYaml $worker.mounts.volumes | nindent 8}}
      {{- end }}
      containers:
        - name: {{ template "dask.fullname" $ }}-worker
          image: "{{ $worker.image.repository }}:{{ $worker.image.tag }}"
          imagePullPolicy: {{ $worker.image.pullPolicy }}
          args:
            - {{ $worker.image.dask_worker }}
          {{- if $worker.custom_scheduler_url }}
            - {{ $worker.custom_scheduler_url }}
          {{- else }}
            - {{ template "dask.fullname" $ }}-scheduler:{{ $.Values.scheduler.servicePort }}
          {{- end }}
          {{- if $worker.resources.limits }}
            - --nthreads
            - {{ $worker.threads_per_worker | default $worker.resources.limits.cpu | default $worker.default_resources.cpu | quote }}
            - --memory-limit
            - {{ $worker.resources.limits.memory | default $worker.default_resources.memory | quote }}
          {{- end }}
            - --no-dashboard
            - --dashboard-address
            - {{ $worker.portDashboard | quote }}
          {{- if $worker.port }}
            - --worker-port
            - {{ $worker.port | quote }}
          {{- end }}
          {{- if $worker.extraArgs }}
            {{ toYaml $worker.extraArgs | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ $worker.portDashboard }}
              name: dashboard
          resources:
            {{- toYaml $worker.resources | nindent 12 }}
          env:
            {{- toYaml $worker.env | nindent 12 }}

          {{- if $worker.mounts.volumeMounts }}
          volumeMounts:
            {{- toYaml $worker.mounts.volumeMounts | nindent 12 }}
          {{- end }}
    {{- with $worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $worker.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if $worker.serviceAccountName }}
      serviceAccountName: {{ $worker.serviceAccountName | quote }}
    {{- end }}
---
{{- end }}
