{{- if and .Values.scheduler.enabled .Values.webUI.ingress.enabled -}}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "dask.fullname" . }}-scheduler
  labels:
    app: {{ template "dask.fullname" . }}-scheduler
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
{{ toYaml .Values.webUI.ingress.annotations | indent 4 }}
spec:
  {{- with .Values.webUI.ingress.ingressClassName }}
  ingressClassName: "{{ . }}"
  {{- end }}
{{- if .Values.webUI.ingress.tls }}
  tls:
    - hosts:
      - {{ .Values.webUI.ingress.hostname | quote }}
      secretName: {{ .Values.webUI.ingress.secretName | default (printf "%s-scheduler-tls" (include "dask.fullname" .)) }}
{{- end }}
  rules:
  - {{- if ne .Values.webUI.ingress.hostname "" }}
    host: {{ .Values.webUI.ingress.hostname }}
    {{- end }}
    http:
      paths:
        - path: /
          {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
          pathType: {{ .Values.webUI.ingress.pathType | default "ImplementationSpecific" }}
          backend:
            service:
              name: {{ template "dask.fullname" . }}-scheduler
              port:
                number: {{ .Values.webUI.servicePort }}
          {{- else }}
          backend:
            serviceName: {{ template "dask.fullname" . }}-scheduler
            servicePort: {{ .Values.webUI.servicePort }}
          {{- end }}
{{- end -}}
