{{- if .Values.scheduler.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "dask.fullname" . }}-scheduler
  labels:
    {{- include "dask.labels" (list .Values.scheduler $) | nindent 4 }}
  {{- with .Values.scheduler.serviceAnnotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: {{ template "dask.fullname" . }}-scheduler
      port: {{ .Values.scheduler.servicePort }}
      targetPort: 8786
    - name: {{ template "dask.fullname" . }}-webui
      port: {{ .Values.webUI.servicePort }}
      targetPort: 8787
  selector:
    {{- include "dask.selectorLabels" (list .Values.scheduler $) | nindent 4 }}
  type: {{ .Values.scheduler.serviceType }}
  {{- with .Values.scheduler.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
{{ end }}
