{{- if and .Values.jupyter.enabled .Values.jupyter.rbac -}}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: dask-jupyter
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dask.selectorLabels" (list .Values.jupyter $) | nindent 4 }}

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dask-jupyter
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dask.selectorLabels" (list .Values.jupyter $) | nindent 4 }}
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods/log"]
  verbs: ["get", "list"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dask-jupyter
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dask.selectorLabels" (list .Values.jupyter $) | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: dask-jupyter
roleRef:
  kind: Role
  name: dask-jupyter
  apiGroup: rbac.authorization.k8s.io
{{- end }}
