{{- if .Values.jupyter.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dask.fullname" . }}-jupyter-config
  labels:
    {{- include "dask.labels" (list .Values.jupyter $) | nindent 4 }}
data:
  jupyter_notebook_config.py: |
    c = get_config()
    c.NotebookApp.password = '{{ .Values.jupyter.password }}'

    {{- with .Values.jupyter.extraConfig }}

    # jupyter.extraConfig follows below
    {{- . | nindent 4 }}
    {{- end }}
{{- end }}
