{{- if and .Values.scheduler.metrics.enabled .Values.scheduler.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "dask.fullname" . }}-scheduler-servicemonitor
  {{- with .Values.scheduler.metrics.serviceMonitor.namespace }}
  namespace: {{ . | quote }}
  {{- end }}
  labels:
    {{- include "dask.labels" (list .Values.scheduler $) | nindent 4 }}
    {{- with .Values.scheduler.metrics.serviceMonitor.additionalLabels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - interval: {{ .Values.scheduler.metrics.serviceMonitor.interval }}
      port: {{ template "dask.fullname" . }}-webui
      {{- with .Values.scheduler.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- . | toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.scheduler.metrics.serviceMonitor.namespaceSelector }}
  namespaceSelector:
    {{- .Values.scheduler.metrics.serviceMonitor.namespaceSelector | toYaml | nindent 4 }}
  {{ else }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  {{- end }}
  {{- with .Values.scheduler.metrics.serviceMonitor.jobLabel }}
  jobLabel: {{ . }}
  {{- end }}
  {{- with .Values.scheduler.metrics.serviceMonitor.targetLabels }}
  targetLabels:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dask.selectorLabels" (list .Values.scheduler $) | nindent 6 }}
{{- end }}
