{{- if .Values.jupyter.rbac -}}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: dask-jupyter
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "dask.name" . }}
    release: {{ .Release.Name | quote }}
    component: jupyter

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dask-jupyter
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "dask.name" . }}
    release: {{ .Release.Name | quote }}
    component: jupyter
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods/log"]
  verbs: ["get", "list"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dask-jupyter
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "dask.name" . }}
    release: {{ .Release.Name | quote }}
    component: jupyter
subjects:
- kind: ServiceAccount
  name: dask-jupyter
roleRef:
  kind: Role
  name: dask-jupyter
  apiGroup: rbac.authorization.k8s.io
{{- end }}
