{{- if and .Values.worker.metrics.enabled .Values.worker.metrics.podMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "dask.fullname" . }}-worker-podmonitor
  {{- with .Values.worker.metrics.podMonitor.namespace }}
  namespace: {{ . | quote }}
  {{- end }}
  labels:
    app: {{ template "dask.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "dask.chart" . }}
    component: worker
    {{- with .Values.worker.metrics.podMonitor.additionalLabels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
spec:
  podMetricsEndpoints:
    - interval: {{ .Values.worker.metrics.podMonitor.interval }}
      port: dashboard
      scheme: http
      {{- with .Values.worker.metrics.podMonitor.metricRelabelings }}
      metricRelabelings:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
  {{- if .Values.worker.metrics.podMonitor.namespaceSelector }}
  namespaceSelector:
    {{- .Values.worker.metrics.podMonitor.namespaceSelector | toYaml | nindent 4 }}
  {{- else }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  {{- end }}
  {{- with .Values.worker.metrics.podMonitor.jobLabel }}
  jobLabel: {{ . }}
  {{- end }}
  {{- with .Values.worker.metrics.podMonitor.targetLabels }}
  podTargetLabels:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ template "dask.name" . }}
      release: {{ .Release.Name | quote }}
      component: worker
{{- end }}
